### PR TITLE
Fix 422 error when attempting to push empty commit

### PR DESCRIPTION
**Pull request by dulek**
This commit adds a check to see if the PR we would create isn't already
merged. To do so it checks if top commit of the dest is a merge commit.
If so, its parents hashes are compared with our merge commit.

### CODE REVIEW

**Comment by dulek** [comment]
@mdbooth: I'm not sure this makes 100% sense, but the problem is exactly in that place I'm attempting to modify.

**Comment by MaysaMacedo** [comment]
/lgtm 
/hold 
It makes sense to me, thanks for the fix. Feel free to remove the hold when you think it's ready to merge.

**Pull request merged**
