### PR TITLE
Allow merging into non-master branches

### PR DESCRIPTION
**Pull request by mandre**
We need this to sync stable branches.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
If I understand your change correctly, the merge-bot will now fetch from upstream (the "source" remote) a branch with the same name of the downstream (the "dest" remote).

Do you think we should make the upstream branch name configurable, so that you can merge, say, "upstream/v1.25" into "dest/v4.12"? Or do you think that we're fine with using the same name for the use cases we currently have?

**Comment by mandre** [comment]
> If I understand your change correctly, the merge-bot will now fetch from upstream (the "source" remote) a branch with the same name of the downstream (the "dest" remote).

That's not what the change does, or at least not what I intended.

The head for the destination branch was mistakenly hardcoded to `master` which I'm changing here to follow the value passed via the `--merge` option.

> Do you think we should make the upstream branch name configurable, so that you can merge, say, "upstream/v1.25" into "dest/v4.12"? Or do you think that we're fine with using the same name for the use cases we currently have?

We already have that with the `--source` and `--merge` options.

**Comment by pierreprinetti** [comment]
OK my Python is rusty... (eh eh)

**Review by pierreprinetti — APPROVED** [review]

**Pull request merged**
